# -*- coding: utf-8 -*-
"""ai_performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAZxgihIoxp5nIoqOI7iCKqDrgEPGUfV
"""

# Basic setup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

# Show all columns
pd.set_option('display.max_columns', None)

# Load data
df = pd.read_csv('/content/synthetic_ai_professional_data.csv')
df.head()

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

import pandas as pd
df = pd.read_csv('/content/synthetic_ai_professional_data.csv')
# Check missing values
print(df.isnull().sum())

# Remove duplicates if any
df.drop_duplicates(inplace=True)

# Quick describe
print(df.describe(include='all'))

#Avg time saved by role
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,5))
sns.barplot(data=df, x='user_role', y='time_saved_per_week', ci=None)
plt.xticks(rotation=90)
plt.title('Average Time Saved by Role')
plt.show()

plt.figure(figsize=(8,5))
sns.barplot(data=df, x='AI_tool_used', y='time_saved_per_week', ci=None)
plt.xticks(rotation=45)
plt.title('Average Time Saved by AI Tool')
plt.show()

#Correlation between satisfaction & performance
plt.figure(figsize=(6,4))
sns.scatterplot(data=df, x='satisfaction_score', y='performance_improvement_pct')
plt.title('Satisfaction vs Performance Improvement')
plt.show()

corr = df['satisfaction_score'].corr(df['performance_improvement_pct'])
print(f"Correlation: {corr:.2f}")

#Remote vs Office Productivity
sns.boxplot(data=df, x='remote_status', y='time_saved_per_week')
plt.title('Remote vs Office Productivity')
plt.show()

# --- Fixed ML Block ---

# Imports (run again just in case)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# Select useful features
features = ['experience_level', 'satisfaction_score', 'performance_improvement_%']
target = 'time_saved_per_week'

# Encode categorical variable (experience_level)
df_encoded = pd.get_dummies(df[['experience_level']], drop_first=True)

# Combine encoded + numeric columns
df_model = pd.concat([df_encoded, df[['satisfaction_score', 'performance_improvement_pct']]], axis=1)

X = df_model
y = df[target]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model training
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Predictions
y_pred = model.predict(X_test_scaled)

# Evaluation
print("R2 Score:", round(r2_score(y_test, y_pred), 3))
print("MAE:", round(mean_absolute_error(y_test, y_pred), 3))

import seaborn as sns
import matplotlib.pyplot as plt

# Avg time saved by role
sns.barplot(data=df, x='user_role', y='time_saved_per_week', hue='experience_level')
plt.xticks(rotation=90)
plt.title("Average Time Saved per Week by Role and Experience Level")
plt.show()

# Correlation heatmap
sns.heatmap(df[['time_saved_per_week', 'satisfaction_score', 'performance_improvement_pct']].corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

# Remote vs Office productivity
sns.boxplot(data=df, x='remote_status', y='performance_improvement_pct')
plt.title("Productivity by Work Mode")
plt.show()

df['predicted_time_saved'] = model.predict(scaler.transform(X))
df.to_csv("ai_productivity_cleaned.csv", index=False)

# --- Convert hours to readable time format (e.g., "5h 30m") ---

def to_hours_minutes(x):
    hours = int(x)
    minutes = int(round((x - hours) * 60))
    return f"{hours}h {minutes}m"

df['time_saved_readable'] = df['time_saved_per_week'].apply(to_hours_minutes)
df['predicted_time_saved_readable'] = df['predicted_time_saved'].apply(to_hours_minutes)

# --- Save final cleaned file ---
df.to_csv("ai_productivity_cleaned.csv", index=False)
print("✅ Saved with readable time columns!")

